name: ZAP Juice Shop Active Scan

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare ZAP context file
        run: mkdir -p /tmp/zap && cp .zap/juice.context /tmp/zap/juice.context

      - name: Run ZAP Full Scan using context file
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://juice-shop.herokuapp.com'
          fail_action: false
          cmd_options: >
            -configfile /tmp/zap/juice.context
            -J report_json.json 
            -w report_md.md 
            -r report_html.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-HTML-Report
          path: report_html.html

      - name: Upload SARIF Report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report_json.sarif
