name: ZAP Juice Shop Active Scan

on:
  push:
    branches:
      - main

permissions: write-all
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan using context file
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: https://juice-shop.herokuapp.com
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          fail_action: false
          cmd_options: >
            -a
            -j
            -n .zap/juice.context

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-HTML-Report
          path: report_html.html
